# Generated by Django 5.2.5 on 2025-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konu',
            name='goruntulenme_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
