# Generated by Django 5.2.5 on 2025-08-22 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_konu_goruntulenme_sayisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cevap',
            name='begenenler',
            field=models.ManyToManyField(blank=True, related_name='begenilen_cevaplar', to=settings.AUTH_USER_MODEL),
        ),
    ]
