# Generated by Django 5.2.5 on 2025-08-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_bildirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='konu',
            name='en_iyi_cevap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.cevap'),
        ),
    ]
