# Generated by Django 5.2.5 on 2025-09-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil_fotolari'),
        ),
    ]
