# Generated by Django 5.2.5 on 2025-09-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_profil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevap',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yanitlar', to='forum.cevap'),
        ),
    ]
