# Generated by Django 5.2.5 on 2025-09-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_cevap_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bildirim',
            name='link',
        ),
        migrations.AddField(
            model_name='bildirim',
            name='bildirim_tipi',
            field=models.CharField(choices=[('BEGENI', 'Beğeni'), ('YANIT', 'Yanıt'), ('CEVAP', 'Cevap')], default='BEGENI', max_length=10),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='ilgili_cevap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.cevap'),
        ),
    ]
