# Generated by Django 5.2.5 on 2025-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_bildirim_link_bildirim_bildirim_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='son_sifre_degistirme',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
