# Generated by Django 5.2.5 on 2025-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_profil_son_sifre_degistirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
