# Generated by Django 5.2.5 on 2025-09-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_profil_ad_soyad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='ad_soyad',
        ),
        migrations.AddField(
            model_name='profil',
            name='gorunen_ad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Görünen Ad'),
        ),
    ]
