# Generated by Django 5.2.5 on 2025-09-20 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_profil_ad_soyad_profil_gorunen_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='konu',
            name='begenenler',
            field=models.ManyToManyField(blank=True, related_name='begenilen_konular', to=settings.AUTH_USER_MODEL),
        ),
    ]
