# Generated by Django 5.2.5 on 2025-09-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_konu_begenenler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cevap',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='konu',
            name='en_iyi_cevap',
        ),
    ]
