# Generated by Django 5.2.5 on 2025-09-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_cevap_parent_remove_konu_en_iyi_cevap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cevap',
            options={'ordering': ['yazilma_tarihi']},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='cevap',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yanitlar', to='forum.cevap'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil_fotolari/'),
        ),
    ]
