# Generated by Django 5.2.5 on 2025-08-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('TSL', 'Taslak'), ('YAY', 'Yayınlandı')], default='TSL', max_length=3),
        ),
    ]
