# Generated by Django 5.2.5 on 2025-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_makale_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='goruntulenme_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
