# Generated by Django 5.2.5 on 2025-08-24 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_makale_goruntulenme_sayisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='begenenler',
            field=models.ManyToManyField(blank=True, related_name='begenilen_makaleler', to=settings.AUTH_USER_MODEL),
        ),
    ]
