# Generated by Django 5.2.5 on 2025-09-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_makale_begenenler'),
        ('forum', '0007_alter_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.kategori'),
        ),
        migrations.DeleteModel(
            name='BlogKategori',
        ),
    ]
